name: Continuous release build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: BsfEditor.sln                              # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build solution
      run: dotnet build $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Move binaries to new ./Output folder, makes a clean artifact zip easier
    - name: Move binaries to Output folder
      uses: Azure/powershell@v2
      with:
        # Specify the Az PowerShell script here.
        inlineScript: |
          New-Item -Name Output -ItemType Directory
          Move-Item -Path .\BsfEditor\bin\*\*\* -Destination ./Output
        # If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream.
        failOnStandardError: true # optional, default is false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Files
        path: ./Output/
